name: Generate Account Age JSON

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (full)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Hitung umur akun & buat JSON
        run: |
          import json
          from datetime import datetime, timezone, timedelta

          # Tanggal akun dibuat (UTC) -> "2023-12-23T07:35:29Z"
          created_at = datetime(2023, 12, 23, 7, 35, 29, tzinfo=timezone.utc)
          now = datetime.now(timezone.utc)

          # Hitung selisih kalender (y, m, d) tanpa library eksternal
          def ymd_diff(start, end):
              y = end.year - start.year
              m = end.month - start.month
              d = end.day - start.day
              if d < 0:
                  # Hari di bulan sebelumnya
                  prev_month = (end.replace(day=1) - timedelta(days=1))
                  d += prev_month.day
                  m -= 1
              if m < 0:
                  m += 12
                  y -= 1
              return y, m, d

          y, m, d = ymd_diff(created_at, now)

          data = {
            "schemaVersion": 1,
            "label": "Account Age",
            "message": f"{y}y {m}m {d}d",
            "color": "blueviolet"
          }

          with open("account-age.json", "w") as f:
              json.dump(data, f)

          print("Badge message:", data["message"])

      - name: Siapkan branch output & commit JSON
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

          # Coba checkout branch output kalau ada; kalau belum ada, buat baru
          if git ls-remote --exit-code --heads origin output; then
            git checkout output
          else
            git checkout -b output
          fi

          mv -f account-age.json account-age.json
          git add account-age.json
          git commit -m "chore: update account age json" || echo "No changes"
          git push origin HEAD:output

      - name: Debug (cek isi JSON yang dipush)
        run: |
          echo "Raw URL:"
          echo "https://raw.githubusercontent.com/${{ github.repository }}/output/account-age.json"
